import {
    multiVariableText,
    text,
    barcodes,
    image,
    svg,
    line,
    table,
    rectangle,
    ellipse,
    dateTime,
    date,
    time,
    select,
    checkbox,
    radioGroup,
} from '@pdfme/schemas';
import { signature } from "./signature";
import fixedVariablesPlugin from "./fixed-variables.ts";

export default {
    Texto: text,
    'Constantes': fixedVariablesPlugin,
    'Sentença com variáveis': multiVariableText,
    Tabela: table,
    Linha: line,
    'Retângulo': rectangle,
    Elipse: ellipse,
    Imagem: image,
    SVG: svg,
    Assinatura: signature,
    'QR Code': barcodes.qrcode,
    'Data e Hora': dateTime,
    Data: date,
    Hora: time,
    'Campo de escolha suspenso': select,
    'Campo de múltipla escolha': checkbox,
    'Campo de escola': radioGroup,
    // JAPANPOST: barcodes.japanpost,
    EAN13: barcodes.ean13,
    // EAN8: barcodes.ean8,
    // Code39: barcodes.code39,
    Code128: barcodes.code128,
    // NW7: barcodes.nw7,
    // ITF14: barcodes.itf14,
    // UPCA: barcodes.upca,
    // UPCE: barcodes.upce,
    // GS1DataMatrix: barcodes.gs1datamatrix,
    // PDF417: barcodes.pdf417,
};
